### ISSUE TITLE
Feature request: Paste in Rules

### ISSUE THREAD

**Issue by TheJaredWilcurt** [g-plane/eslint-playground#53]
Rather than selecting each rule one-by-one, could we either point to a rules repo, or eslintrc, or just paste in some JSON, and have it use those rules?

**Comment by g-plane** [comment]
I'm sorry to tell you that the goal of this playground is for reproducing some cases for one or few rules, so allowing to accept huge ESLint configuration won't be supported.

**Comment by TheJaredWilcurt** [comment]
Sad, yo
